# ============================================
# Shell stage (no tool installed; base image only)
# ============================================
FROM base AS shell

ARG HOME
ARG USER

# SILO_POST_BUILD_HOOKS_SHELL
